### ISSUE TITLE
Plugin installation was unsuccessful due to error "No valid url specified."

### ISSUE THREAD

**Issue by KPSS123** [opendistro/for-elasticsearch#124]
I am using elasticsearch 7.9.1 and kibana 7.9.1.

For the kibana plugins -- 

1) opendistro_index_management-kibana (1.10.1.0, 1.11.0.0)
2) opendistro-anomaly-detection-kibana (1.10.1.0, 1.11.0.0) 

The commands for the installation of the kibana plugin (7.9.1)

"sudo bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-index-management/opendistroIndexManagementKibana-1.10.1.0.zip"

"sudo bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-index-management/opendistroIndexManagementKibana-1.11.0.0.zip"

both these commands are giving the error 

sudo bin/kibana-plugin --allow-root install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-index-management/opendistroIndexManagementKibana-1.11.0.0.zip 
Attempting to transfer from https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-index-management/opendistroIndexManagementKibana-1.11.0.0.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-index-management/opendistroIndexManagementKibana-1.11.0.0.zip/https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-index-management/opendistroIndexManagementKibana-1.11.0.0.zip-7.9.1.zip
Plugin installation was unsuccessful due to error "No valid url specified."

Reference Docs
https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/

Please help to resolve this.

Thank you
Kunal Sisodia

**Comment by stockholmux** [comment]
Hey @KPSS123 - just seeing this. This repo is the website for Open Distro. Looks like you're asking a question about the [index management plugin](https://github.com/opendistro-for-elasticsearch/index-management-kibana-plugin), they can help you over on that repo. I'm going to close it out here.
