### ISSUE TITLE
Refer odfe-cli directly through link

### ISSUE THREAD

**Issue by VijayanB** [opendistro/for-elasticsearch#135]
At this moment, there is no direct link to direct users for cli download from our readme page, closest link is at tool level. It will be great if we could get permanent link, so that user can be directly referred to download section of odfe-cli.

**Comment by stockholmux** [comment]
Fixed in 136. I should note that there is a site-wide bug dealing with the header and hash links that means the header sometimes hides the heading. This will be resolved in the next major revamp of the site.

**Comment by stockholmux** [comment]
Also, link is `https://opendistro.github.io/for-elasticsearch/downloads.html#odfecli`
