### ISSUE TITLE
Document Level Security

### ISSUE THREAD

**Issue by gvsrini** [opendistro/for-elasticsearch#48]
I have ODFE 1.2.0 set with internal users. I have disabled mult-tenancy mode as I am hitting some other issue when enabling it.

Considering multi-tenancy is disabled, I want to configure following DLSQ:

`{ "bool": { "must": { "match": { "roleFilter": "${attr.internal.roleFilter}" } } } }
`

As soon as I add this to my role, following error is thrown when I login with respective user:

`[config:7.2.0]: version conflict, document already exists (current version [2]): [version_conflict_engine_exception] [config:7.2.0]: version conflict, document already exists (current version [2]), with { index_uuid=\"rwRJS4kqQTWcp0p5_vTiHQ\" & shard=\"0\" & index=\".kibana_1\" }
`

If I remove DLSQ (without changing anything else), it starts working again. Also, there is no additional log shown in either Kibana/ES logs.

Any pointers to resolve this?

**Comment by jcgraybill** [comment]
Hi, I'd recommend asking this on the repo for the Security plugin itself: https://github.com/opendistro-for-elasticsearch/security/issues
