### ISSUE TITLE
The downloading libKNNIndex1_7_3_6.zip is not working

### ISSUE THREAD

**Issue by Lyr** [opendistro/for-elasticsearch#64]
During the installation by yum command of the opendistroforelasticsearch-1.4.0-1.noarch package, 
the tool try to download a dependencies at this url :
https://d3g5vo6xdbdb9a.cloudfront.net/downloads/k-NN-lib/libKNNIndex1_7_3_6.zip
Actually, this url doesn't work and return an AccessDenied message. This point blocking the deployment of the solution

**Comment by aetter** [comment]
Hi @Lyr, I'm not able to reproduce. 1.4.0 and 1.6.0 both seem to install cleanly on an RHEL box. Can you try again using the steps here, and if it continues to fail, provide some more details on the exact commands you're running and errors you're receiving? https://opendistro.github.io/for-elasticsearch-docs/docs/install/rpm/

**Comment by Lyr** [comment]
OK, thank for your feedback, I've fixed my issue with a nexus yum repository that have all necessary, so I'm not sure what exactly happens during the install step around yum. I guess this issue could be closed if nobody than me have this same issue.
