### ISSUE TITLE
Missing link to documentation

### ISSUE THREAD

**Issue by gabriel-tessier** [opendistro/for-elasticsearch#8]
in the Readme file there's:
For more documentation, visit https://jekyllrb.com/.

is there a way to have the full path of the documentation?

**Comment by aetter** [comment]
Hi @gabriel-tessier, sure, I've improved the steps and updated the links. https://github.com/opendistro/for-elasticsearch/commit/bc923a6a63da3aefb00b020ee7c53f024a284fc2
