### ISSUE TITLE
Support for {{ctx.monitor.inputs}}

### ISSUE THREAD

**Issue by ScottEnandTM** [opendistro/for-elasticsearch#81]
Currently, in opendistro monitor alert actions, using the mustache `{{#ctx.monitor.inputs}}` does not work. The `Message Preview` section does show what I intend to see, but when I run a test message or the alert triggers automatically, this portion is stripped out of the message sent to Slack in my case.

In particular, I am trying to get the query used to trigger the alert so that I can have a link to the results of the query in the slack message. I am using the mustache syntax `{{#ctx.monitor.inputs}}{{#search.query.query.bool.filter}}{{query_string.query}}{{/search.query.query.bool.filter}}{{/ctx.monitor.inputs}}`. This shows exactly what I want in the `Message Preview` section below the `Message` mustache input box, but the moment the alert is actually triggered, this appears to not return anything and it left blank in the slack message. It appears the `ctx` variable is different for the message preview vs the actual alert it sends.

**Comment by jcgraybill** [comment]
Hi, I'd recommend asking this on the repo for the alerting plugin itself: https://github.com/opendistro-for-elasticsearch/alerting/issues
