### ISSUE TITLE
systemd service opendistro-performance-analyzer.service has the wrong binary path configured

### ISSUE THREAD

**Issue by perkons** [opendistro/for-elasticsearch#94]
Not sure if this is the right place for the issue, but the documentation here https://opendistro.github.io/for-elasticsearch-docs/docs/install/rpm/ has steps to install rmp packages from repo https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo

**OS, OpenDistro and Java version used**:
OS: CentOS Linux release 8.2.2004
OpenDistro: opendistroforelasticsearch-1.10.1-1.noarch
Performance Analyzer: opendistro-performance-analyzer-1.10.1.0-1.noarch
Java: java-11-openjdk-11.0.8.10-0.el8_2.x86_64

**What happened**:
After upgrading OpenDistro from previous to 1.10.1 Performance Analyzer systemd service Failed to start.

This is a rpm package build issue as it seems that the binary path has changed from /usr/share/elasticsearch/bin/performance-analyzer-agent-cli to /usr/share/elasticsearch/plugins/opendistro_performance_analyzer/bin/performance-analyzer-agent-cli but the systemd service file has not been updated.

The file /usr/lib/systemd/system/opendistro-performance-analyzer.service looks like this after install:
```
[Unit]
Description=Opendistro for Elasticsearch Performance Analyzer
PartOf=elasticsearch.service

[Service]
ExecStart=/usr/share/elasticsearch/bin/performance-analyzer-agent-cli
Restart=on-failure
User=elasticsearch
Group=elasticsearch
Environment=ES_HOME=/usr/share/elasticsearch
WorkingDirectory=/usr/share/elasticsearch

[Install]
WantedBy=elasticsearch.service
```
but /usr/share/elasticsearch/bin/performance-analyzer-agent-cli does not exist.
It has been moved to /usr/share/elasticsearch/plugins/opendistro_performance_analyzer/bin/performance-analyzer-agent-cli
also it is not exacutable

**What you expected to happen**:
Opendistro for Elasticsearch Performance Analyzer starts.

**Comment by jcgraybill** [comment]
Hi Perkons, please submit this issue in the [performance-analyzer repo](https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues) and somebody will take a look, thanks.
